#! /usr/bin/bash

if [ ${PWD} == ${REL2} ] ; then
    set -o pipefail
    make $* clobber EPS=1 | tee build.ips.clobber.log
    status=$?
    if [ ${status} -ne 0 ]; then
      echo "clobber for Ips failed ${status}"
      set +o pipefail
      exit ${status}
    fi
    set +o pipefail
    updateIpe
    status=$?
else
    ./mkbuild.enforcer.sh
    status=$?
fi
if [ ${status} -eq 0 ]; then
    copyPKGs
fi
exit ${status}
