#! /usr/bin/bash

set -o pipefail
make $* EPS=1 2>&1 | tee build.ips.log
status=$?
set +o pipefail
if [ ${status} -ne 0 ]; then
  echo "build for Ips failed ${status}"
  set +o pipefail
  exit ${status}
fi
if [ ${status} -ne 0 ]; then
    copyPKGs
fi
exit ${status}
